version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - './:/app'
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300 
    ports:
      - 3000:3000
    command: bash -c "php -S 0.0.0.0:3000 -t /app/public/"
    depends_on:
      - mysql

  phpserver:
    image: php:8.1
    volumes:
      - './:/app'
    ports:
      - 8080:8080
    command: bash -c "php -f /app/src/Server/Server.php"

  phpgameserver:
    image: php:8.1
    volumes:
      - './:/app'
    ports:
      - 8090:8090
    command: bash -c "php -f /app/src/Server/GameServer.php"

  # nginx:
  #   image: nginx:stable-alpine
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./src:/var/www
  #     - ./docker/nginx:/etc/nginx/conf.d 
  #   depends_on:
  #     - php

  mysql:
    image: mysql:8
    # restart: unless-stopped
    command: --init-file /data/application/init_database.sql
    environment:
      - MYSQL_DATABASE=TD
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234

    volumes:
      # - './:/app'
      - ./data/init_database.sql:/data/application/init_database.sql
      - mysqldata:/var/lib/mysql
      # - './docker/volume/mysql:/var/lib/mysql'
    ports:
      - '3307:3306' 

volumes:
    mysqldata: {}